
[keyboard]
bindings = [
    { chars = "\u001BF", key = "Right", mods = "Alt" },
    { chars = "\u001BB", key = "Left", mods = "Alt" },
    { chars = "\u001bOH", key = "Left", mods = "Command" },
    { chars = "\u001bOF", key = "Right", mods = "Command" },
    { chars = "\u0015", key = "Back", mods = "Command" },
    { chars = "\u001b\u007f", key = "Back", mods = "Alt" },
]

[window]
padding.x = 10
padding.y = 10

[font]
size = 12.0

# theme: github dark dimmed
[colors.bright]
black = "0x636e7b"
blue = "0x6cb6ff"
cyan = "0x39c5cf"
green = "0x6bc46d"
magenta = "0xb083f0"
red = "0xff938a"
white = "0x909dab"
yellow = "0xdaaa3f"

[colors.cursor]
cursor = "0xadbac7"
text = "0x22272e"

[colors.normal]
black = "0x545d68"
blue = "0x539bf5"
cyan = "0x39c5cf"
green = "0x57ab5a"
magenta = "0xb083f0"
red = "0xf47067"
white = "0x909dab"
yellow = "0xc69026"

[colors.primary]
background = "0x22272e"
foreground = "0xadbac7"
