"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$kubernetes\
$directory\
$docker_context\
$python\
$git_branch\
"""

[username]
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol]($style)[$hostname]($style) '
disabled = false
ssh_symbol = "🌍 "
trim_at = '-'

[docker_context]
symbol = "🐳"
format = '[$symbol$context]($style) '

[kubernetes]
format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false
contexts = [
    { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
]

[git_branch]
symbol = '🌱 '
truncation_length = 4
truncation_symbol = ''
format = '[$symbol$branch(:$remote_branch)]($style) '

[python]
symbol = "🐍 "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "v${major}.${minor}"
